# Generated by Django 5.2.5 on 2025-08-20 00:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_current_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='profile',
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='budget_range',
            field=models.CharField(choices=[('<10k', '< $10k'), ('10k-25k', '$10k–$25k'), ('25k-50k', '$25k–$50k'), ('50k-100k', '$50k–$100k'), ('>100k', '> $100k')], max_length=50),
        ),
        migrations.AlterField(
            model_name='contactinquiry',
            name='inquiry_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
