# Generated by Django 5.2.5 on 2025-08-23 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_contactinquiry_id_remove_customer_profile_and_more'),
    ]

    operations = [
    ]
