# Generated by Django 5.2.5 on 2025-08-23 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_add_proposal_stage'),
        ('api', '000X_add_proposal_stage'),
    ]

    operations = [
    ]
