# Generated by Django 5.2.5 on 2025-08-23 08:48

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_0005_add_proposal_stage_000X_add_proposal_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='current_stage',
            field=models.ForeignKey(blank=True, default=api.models.get_default_stage_id, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.projectstage'),
        ),
    ]
